name: Generate Snake Animation

on:
  schedule: # roda automaticamente todo dia à meia-noite (UTC)
    - cron: "0 0 * * *"
  workflow_dispatch: # permite rodar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: Joao-ALD
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}